# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(verbose_name='Reservation Date')),
                ('booking_client', models.CharField(max_length=200)),
                ('booking_period', models.IntegerField(choices=[(1, '1st Period'), (2, '2nd Period'), (3, '3rd Period'), (4, '4th Period'), (5, '5th Period'), (6, '6th Period'), (7, '7th Period'), (8, '8th Period')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_text', models.CharField(max_length=10)),
                ('room_no_of_computers', models.IntegerField(default=0)),
                ('room_description', models.CharField(max_length=200)),
                ('room_has_projector', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labreserve.Room'),
        ),
    ]
