# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labreserve', '0004_booking_booking_creator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('booking_date', 'booking_period', 'room')]),
        ),
    ]
