# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labreserve', '0005_auto_20170605_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
