# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labreserve', '0006_auto_20170607_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_creator',
            new_name='booking_owner',
        ),
    ]
