# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labreserve', '0008_auto_20170607_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
