# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-02 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labreserve', '0009_auto_20170607_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': (('room_admin', 'Can Add, Edit, Delete Rooms'),)},
        ),
    ]
