# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-05 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labreserve', '0010_auto_20180102_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(verbose_name='Reservation Date'),
        ),
    ]
