# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labreserve', '0014_auto_20180112_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
