# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-16 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labreserve', '0015_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='room_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
